--- #YAML:1.0
name: CGI-Untaint-Filenames
version: 0.2
author: ~
abstract: |-
  CGI::Untaint::Filenames - untaint filename values from CGI programs
license: perl
provides:
  CGI::Untaint::Filenames:
    file: lib/CGI/Untaint/Filenames.pm
    version: 0.2
generated_by: Module::Build version 0.25
